sudo: required
dist: bionic
language: python
python:
 - "3.8"

before_install:
  - wget -nv https://download.opensuse.org/repositories/home:liberouter/xUbuntu_18.04/Release.key -O Release.key
  - sudo apt-key add - < Release.key
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/liberouter/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/libyang.list"
  - sudo apt-get update
  - sudo apt-get install --allow-unauthenticated libyang

install: 

   - pip install pyang
   - pip install xym
   - pip install xml2rfc

script: 

  - xml2rfc draft-boucadair-dots-rfc8782-yang-update-00.xml
  - pyang –f tree --tree-line-length 69 ietf-dots-signal-channel@2020-07-02.yang
  - yanglint -f yang ietf-dots-signal-channel@2020-07-02.yang
  - yanglint --verbose ietf-dots-signal-channel@2020-07-02.yang -i 
